#include "pch.h"
#include "hook.h"
#include "config.h"
#include "ztl/ztl.h"
#include <cstdint>

#define REPLACE_STRING(INDEX, NEW_STRING) \
    do { \
        EncodeString(INDEX, NEW_STRING); \
    } while (0)


class StringPool {
public:
    class Key {
    public:
        ZArray<uint8_t> m_aKey;
    };
    static_assert(sizeof(Key) == 0x4);
};

static auto StringPool__Key__ctor = reinterpret_cast<void (__thiscall*)(StringPool::Key*, const uint8_t*, uint32_t, uint32_t)>(0x00746470);

static auto StringPool__ms_aKey = reinterpret_cast<const uint8_t*>(0x00B98830);
static auto StringPool__ms_aString = reinterpret_cast<const char**>(0x00C5A878);

constexpr size_t GetLength(const char* s) {
    size_t n = 0;
    while (s[n]) {
        ++n;
    }
    return n;
}

void EncodeString(int nIdx, const char* sSource) {
    StringPool::Key keygen;
    StringPool__Key__ctor(&keygen, StringPool__ms_aKey, 0x10, 0);

    size_t n = strlen(sSource);

    // 动态分配内存，确保生命周期足够长，且不会多次调用相互污染
    char* sDestination = new char[n + 2];

    for (size_t i = 0; i < n; ++i) {
        uint8_t key = keygen.m_aKey[i % 0x10];
        sDestination[i + 1] = sSource[i] ^ key;
        if (static_cast<uint8_t>(sSource[i]) == static_cast<uint8_t>(key)) {
            sDestination[i + 1] = key;
        }
    }
    sDestination[0] = 0;
    sDestination[n + 1] = 0;

    // 修改游戏内存指针
    StringPool__ms_aString[nIdx] = sDestination;
}


void AttachStringPoolMod() {
    REPLACE_STRING(2585, CONFIG_REGISTRY_KEY);
    REPLACE_STRING(2948, CONFIG_VERSION_STRING);
    REPLACE_STRING(9, "Arial");
    REPLACE_STRING(12, "新手");
    REPLACE_STRING(13, "战士");
    REPLACE_STRING(14, "弓箭手");
    REPLACE_STRING(15, "飞侠");
    REPLACE_STRING(16, "海盗");
    REPLACE_STRING(17, "管理员");
    REPLACE_STRING(18, "骑士团");
    REPLACE_STRING(20, "超级管理员");
    REPLACE_STRING(22, "战士");
    REPLACE_STRING(23, "剑客");
    REPLACE_STRING(24, "勇士");
    REPLACE_STRING(25, "英雄");
    REPLACE_STRING(26, "准骑士");
    REPLACE_STRING(27, "骑士");
    REPLACE_STRING(28, "圣骑士");
    REPLACE_STRING(29, "枪战士");
    REPLACE_STRING(30, "龙骑士");
    REPLACE_STRING(31, "黑骑士");
    REPLACE_STRING(32, "法师");
    REPLACE_STRING(33, "巫师");
    REPLACE_STRING(34, "魔导师");
    REPLACE_STRING(35, "法师(火,毒)");
    REPLACE_STRING(36, "巫师(火,毒)");
    REPLACE_STRING(37, "魔导师(火,毒)");
    REPLACE_STRING(38, "法师(冰,雷)");
    REPLACE_STRING(39, "巫师(冰,雷)");
    REPLACE_STRING(40, "魔导师(冰,雷)");
    REPLACE_STRING(41, "牧师");
    REPLACE_STRING(42, "祭司");
    REPLACE_STRING(43, "主教");
    REPLACE_STRING(44, "弓箭手");
    REPLACE_STRING(45, "猎人");
    REPLACE_STRING(46, "射手");
    REPLACE_STRING(47, "神射手");
    REPLACE_STRING(48, "弩弓手");
    REPLACE_STRING(49, "游侠");
    REPLACE_STRING(50, "箭神");
    REPLACE_STRING(51, "飞侠");
    REPLACE_STRING(52, "刺客");
    REPLACE_STRING(53, "无影人");
    REPLACE_STRING(54, "隐士");
    REPLACE_STRING(55, "侠客");
    REPLACE_STRING(56, "独行客");
    REPLACE_STRING(57, "侠盗");
    REPLACE_STRING(58, "拳手");
    REPLACE_STRING(59, "斗士");
    REPLACE_STRING(60, "冲锋队长");
    REPLACE_STRING(61, "火枪手");
    REPLACE_STRING(62, "大副");
    REPLACE_STRING(63, "船长");
    REPLACE_STRING(64, "初心者");
    REPLACE_STRING(123, "/悄悄话");
    REPLACE_STRING(124, "/组队");
    REPLACE_STRING(126, "/好友");
    REPLACE_STRING(127, "/家族");
    REPLACE_STRING(128, "/联盟");
    REPLACE_STRING(129, "/配偶");
    REPLACE_STRING(130, "/所有人");
    REPLACE_STRING(131, "/找人");
    REPLACE_STRING(132, "/交易");
    REPLACE_STRING(135, "/队伍信息");
    REPLACE_STRING(136, "/创建队伍");
    REPLACE_STRING(137, "/离开队伍");
    REPLACE_STRING(138, "/队伍邀请");
    REPLACE_STRING(154, "找不到 %s");
    REPLACE_STRING(155, "%s 在 %s。");
    REPLACE_STRING(156, "%s 目前正在现金商城。");
    REPLACE_STRING(157, "%s 目前在 %s。");
    REPLACE_STRING(158, "%s 目前在活动地图。");
    REPLACE_STRING(159, "%s 拒绝悄悄话。");
    REPLACE_STRING(160, "你没有队伍或者没有队员在线");
    REPLACE_STRING(161, "你没有结婚或者对象不在线");
    REPLACE_STRING(162, "你没有在线的好友");
    REPLACE_STRING(163, "你没有家族或者没有成员在线");
    REPLACE_STRING(278, "你现在还不能这么做。\r\n请稍后再试。");
    REPLACE_STRING(280, "当前位置无法查看大地图");
    REPLACE_STRING(283, "此 NPC 位于世界\r\n地图上无法找到的地点。");
    REPLACE_STRING(288, "无法在彩虹岛使用");
    REPLACE_STRING(289, "当前地图无法使用");
    REPLACE_STRING(290, "当前地图无法进行");
    REPLACE_STRING(291, "你无法移动到其他岛屿");
    REPLACE_STRING(294, "得到经验值 (+%d)");
    REPLACE_STRING(295, "网吧经验加成 (+%d)");
    REPLACE_STRING(296, "活动经验加成 (+%d)");
    REPLACE_STRING(297, "结婚经验加成 (+%d)");
    REPLACE_STRING(298, "装备经验加成 (+%d)");
    REPLACE_STRING(301, "获得人气度 (+%d)");
    REPLACE_STRING(302, "人气度减少 (%d)");
    REPLACE_STRING(303, "获取金币 (+%d)");
    REPLACE_STRING(304, "网吧金币加成 (+%d)");
    REPLACE_STRING(305, "金币减少  (%d)");
    REPLACE_STRING(306, "丢弃物品 (%s %d个)");
    REPLACE_STRING(307, "丢弃物品 (%s)");
    REPLACE_STRING(308, "不能拣取物品");
    REPLACE_STRING(309, "[%s]已过期，道具被清除了。");
    REPLACE_STRING(310, "正在处理其他请求，请再试一次。");
    REPLACE_STRING(311, "增加 %s 的人气度。");
    REPLACE_STRING(312, "降低了 %s 的人气度。");
    REPLACE_STRING(314, "低于15级无法使用人气功能");
    REPLACE_STRING(315, "你今天无法使用人气功能了");
    REPLACE_STRING(316, "你这个月无法对该玩家使用人气功能");
    REPLACE_STRING(317, "%s 增加了 %s 的人气");
    REPLACE_STRING(318, "%s 降低了 %s 的人气");
    REPLACE_STRING(320, "请稍后再试。");
    REPLACE_STRING(321, "%s 未开启组队邀请。");
    REPLACE_STRING(322, "%s 拒绝了组队邀请。");
    REPLACE_STRING(323, "你创建了一个新队伍。");
    REPLACE_STRING(324, "你被队长移除了");
    REPLACE_STRING(325, "你离开了队伍");
    REPLACE_STRING(326, "%s 被队伍移除");
    REPLACE_STRING(327, "%s 离开了队伍。");
    REPLACE_STRING(328, "你作为队长退出了队伍，队伍解散了。");
    REPLACE_STRING(329, "因为队长退出，队伍解散了。");
    REPLACE_STRING(330, "你加入了队伍。");
    REPLACE_STRING(331, "%s 加入了队伍。");
    REPLACE_STRING(332, "已经加入队伍了。");
    REPLACE_STRING(333, "新手不能创建队伍");
    REPLACE_STRING(334, "你没有加入队伍");
    REPLACE_STRING(335, "对方队伍满员了");
    REPLACE_STRING(336, "你不是队长");
    REPLACE_STRING(337, "你不能邀请你自己入队");
    REPLACE_STRING(338, "%s 不是队伍成员");
    REPLACE_STRING(344, "队员: ");
    REPLACE_STRING(345, "你是队长");
    REPLACE_STRING(347, "%s 没有开启组队邀请");
    REPLACE_STRING(348, "%s 拒绝了家族邀请");
    REPLACE_STRING(349, "你加入了 %s 家族");
    REPLACE_STRING(350, "新家族成立了");
    REPLACE_STRING(351, "你退出了家族");
    REPLACE_STRING(352, "%s 被踢出家族");
    REPLACE_STRING(354, "%s 离开了家族");
    REPLACE_STRING(355, "要踢出 %s 吗？");
    REPLACE_STRING(356, "你要离开家族吗？");
    REPLACE_STRING(357, "%s 离开了家族");
    REPLACE_STRING(358, "家族解散了");
    REPLACE_STRING(359, "加入了家族");
    REPLACE_STRING(360, "%s 加入了家族");
    REPLACE_STRING(361, "已经有家族了");
    REPLACE_STRING(363, "没有加入家族");
    REPLACE_STRING(364, "你是族长无法退出家族");
    REPLACE_STRING(365, "你申请的家族已经满人了");
    REPLACE_STRING(367, "你不是族长");
    REPLACE_STRING(368, "你不能邀请自己加入家族");
    REPLACE_STRING(369, "%s 不是家族成员");
    REPLACE_STRING(370, "只有族长可以踢出副族长");
    REPLACE_STRING(373, "你无法邀请更多人加入家族");
    REPLACE_STRING(374, "由于未知原因，家族请求被拒绝了");
    REPLACE_STRING(375, "当前频道无法找到该玩家");
    REPLACE_STRING(376, "家族成员: ");
    REPLACE_STRING(377, "你是族长");
    REPLACE_STRING(378, "家族成员上限提高到了 %d");
    REPLACE_STRING(379, "无法找到该玩家");
    REPLACE_STRING(380, "已经加过该好友了");
    REPLACE_STRING(381, "你不能加自己为好友");
    REPLACE_STRING(382, "找不到该玩家");
    REPLACE_STRING(383, "你无法添加该玩家为好友");
    REPLACE_STRING(384, "你已经发送过好友申请，请稍后再试。");
    REPLACE_STRING(385, "传送点目前处于关闭状态");
    REPLACE_STRING(394, "亲密度增加 (+%d)");
    REPLACE_STRING(395, "亲密度降低 (%d)");
    REPLACE_STRING(396, "宠物由于太饥饿，已经回家了。");
    REPLACE_STRING(397, "由于宠物的魔法时间已经结束，宠物变成了娃娃。");
    REPLACE_STRING(398, "这里不允许使用宠物。");
    REPLACE_STRING(402, "卷轴发出一道亮光，在道具上添加了某种神秘的能力。");
    REPLACE_STRING(403, "卷轴发出一道亮光，但是道具没有任何变化。");
    REPLACE_STRING(404, "因为卷轴的力量，道具消失了。");
    REPLACE_STRING(405, "想用 <%s> 音乐箱奏曲吗？");
    REPLACE_STRING(409, "房间已经关闭了");
    REPLACE_STRING(429, "请输入商店名称\r\n\r\n如果你在开店前离开\r\n商店可能会创建失败。");
    REPLACE_STRING(430, "每 %d 个售价 %s 金币");
    REPLACE_STRING(431, "售价 %s 金币");
    REPLACE_STRING(432, "商店关闭了");
    REPLACE_STRING(433, "物品卖光了");
    REPLACE_STRING(435, "总价是 %d 金币\r\n你要购买吗？");
    REPLACE_STRING(442, "道具已经卖掉了");
    REPLACE_STRING(450, "必须在自由市场中开设商店。");
    REPLACE_STRING(502, "扩展 %s 栏空间 (%d 点券)\r\n请确认。");
    REPLACE_STRING(503, "扩展仓库空间 (%d 点券)\r\n请确认。");
    REPLACE_STRING(504, "扩展角色槽 (%d 点券)\r\n请确认。");
    REPLACE_STRING(515, "你已经有这个道具了。\r\n你要再次购买吗？");
    REPLACE_STRING(523, "你确定你要买这个道具吗？");
    REPLACE_STRING(544, "你已经把这个道具加到愿望清单里了。");
    REPLACE_STRING(545, "愿望列表满了");
    REPLACE_STRING(546, "购买成功");
    REPLACE_STRING(548, "扩展了背包空间");
    REPLACE_STRING(549, "增加了一个角色槽");
    REPLACE_STRING(553, "点券不足");
    REPLACE_STRING(590, "已添加到愿望列表");
    REPLACE_STRING(591, "[宠物] %s");
    REPLACE_STRING(592, "增加仓库空间");
    REPLACE_STRING(593, "增加仓库 %d 个格子 (当前：%d 格子)\r\n上限 48 格子。价格：%d 点券。");
    REPLACE_STRING(594, "增加仓库 %d 个格子 (当前：%d)\r\n上限 48 格子。");
    REPLACE_STRING(595, "增加 %s 空间");
    REPLACE_STRING(596, "增加 %d 个格子到 %s 栏。 (当前：%d 格子)\r\n上限 %d 格子。价格%d 点券。");
    REPLACE_STRING(597, "增加 %d 个格子到 %s 栏。 (当前：%d 格子)\r\n上限 %d 格子。");
    REPLACE_STRING(598, "增加角色槽 (当前：%d 个)\r\n上限 %d 个。");
    REPLACE_STRING(604, "%d 抵用券");
    REPLACE_STRING(605, "%d 金币");
    REPLACE_STRING(615, "强化宝石");
    REPLACE_STRING(616, "怪物结晶");
    REPLACE_STRING(617, "分解装备");
    REPLACE_STRING(618, "单手剑");
    REPLACE_STRING(619, "单手斧");
    REPLACE_STRING(620, "单手钝器");
    REPLACE_STRING(621, "短刀");
    REPLACE_STRING(622, "短杖");
    REPLACE_STRING(623, "长杖");
    REPLACE_STRING(624, "双手剑");
    REPLACE_STRING(625, "双手斧");
    REPLACE_STRING(626, "双手钝器");
    REPLACE_STRING(627, "枪");
    REPLACE_STRING(628, "矛");
    REPLACE_STRING(629, "弓");
    REPLACE_STRING(630, "弩");
    REPLACE_STRING(631, "拳套");
    REPLACE_STRING(632, "指节");
    REPLACE_STRING(633, "短枪");
    REPLACE_STRING(634, "帽子");
    REPLACE_STRING(635, "脸饰");
    REPLACE_STRING(636, "眼饰");
    REPLACE_STRING(637, "耳环");
    REPLACE_STRING(638, "套服");
    REPLACE_STRING(639, "上衣");
    REPLACE_STRING(640, "裤/裙");
    REPLACE_STRING(641, "鞋子");
    REPLACE_STRING(642, "手套");
    REPLACE_STRING(643, "披风");
    REPLACE_STRING(644, "盾牌");
    REPLACE_STRING(645, "戒指");
    REPLACE_STRING(646, "坠子");
    REPLACE_STRING(647, "勋章");
    REPLACE_STRING(648, "腰带");
    REPLACE_STRING(649, "全身铠甲");
    REPLACE_STRING(650, "武器");
    REPLACE_STRING(651, "单手武器");
    REPLACE_STRING(652, "双手武器");
    REPLACE_STRING(661, "最快");
    REPLACE_STRING(662, "快+");
    REPLACE_STRING(663, "快");
    REPLACE_STRING(664, "普通");
    REPLACE_STRING(665, "慢");
    REPLACE_STRING(666, "慢+");
    REPLACE_STRING(667, "最慢");
    REPLACE_STRING(668, "%s 赠送");
    REPLACE_STRING(669, "有效期 %d 天");
    REPLACE_STRING(670, "有效期 4 小时");
    REPLACE_STRING(671, "有效期 %d 小时");
    REPLACE_STRING(672, "有效期至 %04d/%d/%d %02d : %02d");
    REPLACE_STRING(673, "攻击速度 : ");
    REPLACE_STRING(674, "攻击力 :");
    REPLACE_STRING(675, "魔法力 :");
    REPLACE_STRING(676, "物理防御 :");
    REPLACE_STRING(677, "魔法防御 :");
    REPLACE_STRING(678, "命中 :");
    REPLACE_STRING(679, "回避 :");
    REPLACE_STRING(680, "手技 :");
    REPLACE_STRING(681, "移动速度 :");
    REPLACE_STRING(682, "跳跃力 :");
    REPLACE_STRING(683, "游泳速度 : +%d");
    REPLACE_STRING(684, "击退概率 :");
    REPLACE_STRING(685, "可升级次数 :");
    REPLACE_STRING(688, "由 %s 赠送");
    REPLACE_STRING(689, "和 %s 的情侣戒指");
    REPLACE_STRING(690, "和 %s 的友情戒指");
    REPLACE_STRING(691, "[当前等级 %d]");
    REPLACE_STRING(692, "[下一等级 %d]");
    REPLACE_STRING(693, "魔法时间 : %d 天");
    REPLACE_STRING(694, "魔法时间 : %d 小时 %d 分钟");
    REPLACE_STRING(695, "生命之水的力量已枯竭");
    REPLACE_STRING(696, "生命之水将于 %04d年%d月%d日 %02d时 枯竭");
    REPLACE_STRING(698, "在线好友 / 所有好友");
    REPLACE_STRING(699, "离线好友 / 所有好友");
    REPLACE_STRING(701, "在线成员 / 所有成员");
    REPLACE_STRING(702, "离线成员 / 所有成员");
    REPLACE_STRING(703, "按名字排序");
    REPLACE_STRING(704, "按职业排序");
    REPLACE_STRING(705, "按等级排序");
    REPLACE_STRING(706, "按职位排序");
    REPLACE_STRING(708, "玩家在另外一个地方");
    REPLACE_STRING(709, "唯一道具");
    REPLACE_STRING(710, "任务道具");
    REPLACE_STRING(711, "组队任务道具");
    REPLACE_STRING(712, "无法交易");
    REPLACE_STRING(713, "(转移后无法交易)");
    REPLACE_STRING(714, "道具合并");
    REPLACE_STRING(715, "道具排序");
    REPLACE_STRING(716, "装备后无法交易");
    REPLACE_STRING(726, "我的位置 - %s");
    REPLACE_STRING(727, "%s 在 %s");
    REPLACE_STRING(731, "好友 %s ");
    REPLACE_STRING(732, "上线了");
    REPLACE_STRING(733, "进入了当前频道");
    REPLACE_STRING(734, "好友 %s");
    REPLACE_STRING(735, "由于未知原因，请求被拒绝了。");
    REPLACE_STRING(736, "你的好友列表满了");
    REPLACE_STRING(737, "对方好友列表满了");
    REPLACE_STRING(738, "该玩家已经是你的好友了");
    REPLACE_STRING(741, "输入你想拉黑的角色名");
    REPLACE_STRING(742, "你不能拉黑你自己");
    REPLACE_STRING(743, "无法登录该玩家");
    REPLACE_STRING(745, "你的好友已离线，无法发送悄悄话。");
    REPLACE_STRING(753, "请选择你要制作的道具");
    REPLACE_STRING(754, "背包满了");
    REPLACE_STRING(755, "无法添加该道具");
    REPLACE_STRING(756, "已经有道具防止在此了");
    REPLACE_STRING(757, "不能放入更多材料了");
    REPLACE_STRING(758, "这里只能放入强化宝石");
    REPLACE_STRING(759, "不能放入更多强化宝石了");
    REPLACE_STRING(760, "不能放入相同的强化宝石");
    REPLACE_STRING(761, "该强化宝石只能给武器使用");
    REPLACE_STRING(762, "此处只能放入辅助剂");
    REPLACE_STRING(763, "只能放入1个辅助剂");
    REPLACE_STRING(764, "不能放入该辅助剂");
    REPLACE_STRING(765, "你不能使用该道具作为制作怪物结晶的材料");
    REPLACE_STRING(766, "由于未知原因，制作失败");
    REPLACE_STRING(767, "成功制作了 %d 个 %s");
    REPLACE_STRING(768, "成功分解了 %s");
    REPLACE_STRING(769, "制作失败");
    REPLACE_STRING(770, "物品被摧毁了");
    REPLACE_STRING(771, "你想使用多少个？");
    REPLACE_STRING(772, ": 你确定要制作这个吗？");
    REPLACE_STRING(773, "你确定要合成怪物结晶吗？");
    REPLACE_STRING(774, "你确定要分解吗？");
    REPLACE_STRING(775, "你确定要制作吗？");
    REPLACE_STRING(776, "将怪物材料放置于此\r\n制作怪物结晶");
    REPLACE_STRING(777, "将装备放置于此\r\n分解后获得怪物结晶");
    REPLACE_STRING(778, "输入你想邀请的玩家名");
    REPLACE_STRING(779, "来自 %s");
    REPLACE_STRING(780, "聊天邀请");
    REPLACE_STRING(781, "好友请求");
    REPLACE_STRING(782, "交易申请");
    REPLACE_STRING(783, "组队邀请");
    REPLACE_STRING(784, "家族邀请");
    REPLACE_STRING(785, "学院邀请");
    REPLACE_STRING(786, "新任务！");
    REPLACE_STRING(787, "任务完成！");
    REPLACE_STRING(798, "请输入你想发送悄悄话的玩家");
    REPLACE_STRING(799, "玩家名错误");
    REPLACE_STRING(800, "不要自言自语");
    REPLACE_STRING(802, "对所有人");
    REPLACE_STRING(803, "对组队");
    REPLACE_STRING(804, "对好友");
    REPLACE_STRING(805, "对配偶");
    REPLACE_STRING(806, "对家族");
    REPLACE_STRING(807, "对分组");
    REPLACE_STRING(816, "[ MapleHero 聊天室 ]");
    REPLACE_STRING(817, "邀请 : /邀请 玩家名称");
    REPLACE_STRING(818, "结束 : /q");
    REPLACE_STRING(819, "- %s 进来了");
    REPLACE_STRING(820, "- 你无法加入受邀的聊天室");
    REPLACE_STRING(821, "- %s 离开了");
    REPLACE_STRING(822, "- 请输入玩家名称");
    REPLACE_STRING(823, "- 玩家名称不合法");
    REPLACE_STRING(824, " 正在输入");
    REPLACE_STRING(831, "安装目录");
    REPLACE_STRING(832, "桌面");
    REPLACE_STRING(834, "不能低于 %d");
    REPLACE_STRING(835, "不能高于 %d");
    REPLACE_STRING(839, "请输入家族名称。");
    REPLACE_STRING(865, "确定购买？");
    REPLACE_STRING(866, "你要买入多少？");
    REPLACE_STRING(867, "确定出售？");
    REPLACE_STRING(868, "你要卖出多少？");
    REPLACE_STRING(870, "请检查背包已满");
    REPLACE_STRING(875, "确定要给这个物品充值吗？？");
    REPLACE_STRING(876, "你要从仓库中取出该道具吗？");
    REPLACE_STRING(877, "取出该道具需要支付 %d 金币。");
    REPLACE_STRING(878, "你确定要存放这个道具吗？");
    REPLACE_STRING(879, "存放物品将收取 %d 金币。\r\n你想存放物品吗？");
    REPLACE_STRING(880, "你想存入多少？");
    REPLACE_STRING(881, "你想取出多少金币？");
    REPLACE_STRING(882, "你想存入多少金币？");
    REPLACE_STRING(883, "仓库满了。");
    REPLACE_STRING(885, "装备后该道具将无法交易\r\n你确定要装备吗？");
    REPLACE_STRING(886, "属性不足以使用该装备");
    REPLACE_STRING(896, "当前宠物无法穿戴这个道具。");
    REPLACE_STRING(897, "%s 不能装备\r\n这个物品。");
    REPLACE_STRING(898, "你没有一只宠物可以穿戴这个道具。");
    REPLACE_STRING(899, "当前地图禁止更换装备。");
    REPLACE_STRING(901, "这个宠物无法穿戴宠物装备。");
    REPLACE_STRING(902, "管理员禁止丢弃道具。");
    REPLACE_STRING(903, "你不能丢弃这个道具。");
    REPLACE_STRING(904, "当前地图禁止修改属性。");
    REPLACE_STRING(905, "当前地图禁止使用这个技能。");
    REPLACE_STRING(906, "你想丢弃多少？");
    REPLACE_STRING(907, "这个道具无法交易给别人。");
    REPLACE_STRING(908, "你想拿多少来交易？");
    REPLACE_STRING(909, "[欢迎信息] 欢迎来到 MapleHero!");
    REPLACE_STRING(910, "[帮助]");
    REPLACE_STRING(911, "[注意]");
    REPLACE_STRING(927, "无法连接");
    REPLACE_STRING(962, "男");
    REPLACE_STRING(963, "女");
    REPLACE_STRING(1667, "经验");
    REPLACE_STRING(1991, "    属性点将自动分配:\r\n\r\n");
    REPLACE_STRING(2048, "等级 : %d");
    REPLACE_STRING(2049, "[需求]");
    REPLACE_STRING(2441, "装备(%s)");
    REPLACE_STRING(2442, "道具(%s)");
    REPLACE_STRING(2443, "属性(%s)");
    REPLACE_STRING(2444, "技能(%s)");
    REPLACE_STRING(2663, "买家 : %s");
    REPLACE_STRING(2664, "数量 : %d");
    REPLACE_STRING(2665, "销售 / 收入");
    REPLACE_STRING(2884, "你没有足够的 HP 释放这个技能");
    REPLACE_STRING(2885, "你没有足够的 MP 释放这个技能");
    REPLACE_STRING(2886, "你没有足够的 金币 释放这个技能");
    REPLACE_STRING(2887, "你没有足够的 %s 释放这个技能");
    REPLACE_STRING(2888, "你没有足够的 飞镖 释放这个技能");
    REPLACE_STRING(2889, "你没有足够的 子弹 释放这个技能");
    REPLACE_STRING(2890, "当前武器无法释放该技能");
    REPLACE_STRING(2891, "当前属性无法装备该道具");
    REPLACE_STRING(2892, "你没有装备武器，无法攻击");
    REPLACE_STRING(2893, "只有HP药水可以使用");
    REPLACE_STRING(2894, "只有MP药水可以使用");
    REPLACE_STRING(2895, "箭矢用完了");
    REPLACE_STRING(2896, "飞镖用完了");
    REPLACE_STRING(2959, "你被封印了，无法释放技能。");
    REPLACE_STRING(2960, "你被虚弱了，无法跳跃。");
    REPLACE_STRING(2961, "你被晕眩了，无法移动。");
    REPLACE_STRING(2962, "你被诅咒了，获得的经验值减半。");
    REPLACE_STRING(2963, "你进入了黑暗状态，命中率下降。");
    REPLACE_STRING(2964, "你中毒了，HP正在减少。");
    REPLACE_STRING(3000, "你要记录这个地方吗？\r\n[%s]");
    REPLACE_STRING(3019, "排名不可用");
    REPLACE_STRING(3020, "第 %d 名");
    REPLACE_STRING(3184, "有效期到 %04d/%d/%d %02d:%02d");
    REPLACE_STRING(3271, "达到 %d 级");
    REPLACE_STRING(3272, "%s 低于 %d 级");
    REPLACE_STRING(3286, "完成于 %d年%d月%d日 %02d时");
    REPLACE_STRING(3291, "你确定要放弃这个任务吗？");
    REPLACE_STRING(3292, "背包 %s 栏满了");
    REPLACE_STRING(3296, "族长");
    REPLACE_STRING(3297, "副族长");
    REPLACE_STRING(3298, "成员");
    REPLACE_STRING(3311, "名字已被使用");
    REPLACE_STRING(3312, "恭喜~  家族 %s 已经创建成功！祝你好运！");
    REPLACE_STRING(3313, "家族已经解散，如果你还想创建家族，请来找我。");
    REPLACE_STRING(3328, "[%s] 的家族地位变更为 [%s].");
    REPLACE_STRING(3329, "已保存");
    REPLACE_STRING(3332, "请输入新的名称");
    REPLACE_STRING(3333, "无法删除该职位\r\n这不是最低级的职位");
    REPLACE_STRING(3334, "无法删除该职位\r\n还有成员属于这个职位");
    REPLACE_STRING(3335, "你要保存修改吗？");
    REPLACE_STRING(3372, "你要将这个保存为家族徽章吗？");
    REPLACE_STRING(3373, "完成了");
    REPLACE_STRING(3376, "无法切换频道，请稍后再试。");
    REPLACE_STRING(3377, "无法进入商城，请稍后再试。");
    REPLACE_STRING(3380, "[%s] 任务已过期。从任务列表中移除。");
    REPLACE_STRING(3381, "* 家族公告");
    REPLACE_STRING(3382, "* 家族公告 : %s");
    REPLACE_STRING(3383, "请输入家族公告");
    REPLACE_STRING(3465, "宠物设置的HP药水用完，请补充。");
    REPLACE_STRING(3466, "宠物设置的MP药水用完，请补充。");
    REPLACE_STRING(3467, "宠物将在HP低于警戒值时自动帮你吃药。");
    REPLACE_STRING(3468, "宠物将在MP低于警戒值时自动帮你吃药。");
    REPLACE_STRING(3494, "%s 的雇佣商店");
    REPLACE_STRING(3496, "%s 的雇佣商店 : %s");
    REPLACE_STRING(3500, "所有未取出的商品和金币将寄存到市场入口的弗兰德里");
    REPLACE_STRING(3501, "管理商店时无法出售道具，你要管理商店吗？");
    REPLACE_STRING(3502, "商店正在维护");
    REPLACE_STRING(3504, "收铺倒计时  / %02d : %02d");
    REPLACE_STRING(3505, "你的商店目前开在\r\n%s 线, 自由市场 %d 洞\r\n请先关闭商店才可以重新创建。");
    REPLACE_STRING(3511, "清理掉卖光的物品，并取回获得的金币");
    REPLACE_STRING(3521, "你没有东西存在我这里");
    REPLACE_STRING(3522, "你的商店开在 #b%s 线，%d 洞#k。\r\n请先关闭商店再来找我");
    REPLACE_STRING(3523, "目前不可用，请稍后再试");
    REPLACE_STRING(3524, "你的物品已经存放了 %d 天。\r\n你需要花费 %d%% 的手续费，\r\n%d 金币。\r\n你要取回物品吗？");
    REPLACE_STRING(3525, "你要取回保存的物品吗？");
    REPLACE_STRING(3526, "取回了全部物品和金币");
    REPLACE_STRING(3527, "由于身上的金币太多装不下，取回失败");
    REPLACE_STRING(3528, "身上和仓库存在相同的唯一道具，取回失败");
    REPLACE_STRING(3529, "金币不足无法取回保管的物品");
    REPLACE_STRING(3530, "背包满了无法取回保管的物品");
    REPLACE_STRING(3531, "请找弗兰迪克取回寄存的道具");
    REPLACE_STRING(3532, "您好~我是雇用商人委员会的代表弗兰德里。雇用商人的使用方法与一般商店大致相同，只需注意几点注意事项。\r\n\r\n#r注意事项\r\n#k无论#r如何形式的关闭商店#k，道具和金币都会存入我这里保管，你需要在我这取回。\r\n目前服务器没有设立保管费，也没有暂存物品时无法开店的设定，你可以自行选择何时取回寄存的道具。");
    REPLACE_STRING(3540, "请先将符合条件的宠物召唤出来");
    REPLACE_STRING(3541, "当前召唤的宠物不满足任务条件");
    REPLACE_STRING(3579, "你已连续在线 %d 小时。");
    REPLACE_STRING(3580, "你已连续在线 %d 小时。\r\n建议你休息一下。");
    REPLACE_STRING(3617, "要离开聊天室吗？");
    REPLACE_STRING(3637, "技能还在冷却中");
    REPLACE_STRING(3660, "任务指引 (%d/5)");
    REPLACE_STRING(3852, "怪物装备");
    REPLACE_STRING(3853, "宠物装备");
    REPLACE_STRING(3854, "宠物指环");
    REPLACE_STRING(3867, "背包空间不足");
    REPLACE_STRING(3868, "背包 其他栏 空间不足");
    REPLACE_STRING(3889, "无法使用 %s。");
    REPLACE_STRING(3894, "[最高等级 : %d]");
    REPLACE_STRING(3959, "[输入答案]");
    REPLACE_STRING(3960, "在规定时间内输入答案。");
    REPLACE_STRING(4086, "你确定要转让队长给\r\n%s？");
    REPLACE_STRING(4087, "%s成为了队长");
    REPLACE_STRING(4088, "由于队长离线了，%s被指定为新的队长。");
    REPLACE_STRING(4089, "队友不在附近");
    REPLACE_STRING(4090, "队友不在相同频道");
    REPLACE_STRING(4106, "你收到一个新的任务，双击头顶的灯泡查看。");
    REPLACE_STRING(4164, "PIC 需要至少要有 %d 位");
    REPLACE_STRING(4165, "再次输入PIC");
    REPLACE_STRING(4211, "有人在 MapleHero 中给你留言。");
    REPLACE_STRING(4218, "自动登记：开启");
    REPLACE_STRING(4219, "自动登记：关闭");
    REPLACE_STRING(4220, "点击后开启，当任务进度更新时会自动跟踪，超过10分钟没有变化的任务将暂停跟踪。");
    REPLACE_STRING(4221, "点击后关闭，只能手动添加要跟踪的任务。");
    REPLACE_STRING(4228, "不显示");
    REPLACE_STRING(4229, "只显示名称");
    REPLACE_STRING(4230, "只显示HP");
    REPLACE_STRING(4231, "显示名称和HP");
    REPLACE_STRING(4235, "无法对这个道具使用卷轴");
    REPLACE_STRING(4314, "未开始");
    REPLACE_STRING(4315, "进行中");
    REPLACE_STRING(4316, "可完成");
    REPLACE_STRING(4341, "将鼠标移动到");
    REPLACE_STRING(4342, "技能图标上");
    REPLACE_STRING(4343, "查看当前技能");
    REPLACE_STRING(4344, "的详情");
    REPLACE_STRING(4345, "单机这个");
    REPLACE_STRING(4346, "按钮");
    REPLACE_STRING(4347, "提升");
    REPLACE_STRING(4348, "技能等级");
    REPLACE_STRING(4349, "你可以使用");
    REPLACE_STRING(4350, "技能点来");
    REPLACE_STRING(4351, "提升你的");
    REPLACE_STRING(4352, "技能等级");
    REPLACE_STRING(4358, "打开/关闭技能宏界面");
    REPLACE_STRING(4359, "从技能栏拖动技能\r\n到这个插槽");
    REPLACE_STRING(4360, "保存技能宏名称");
    REPLACE_STRING(4391, "当前装备的武器无法使用该技能");
    REPLACE_STRING(4392, "无法在这里使用");
    REPLACE_STRING(4438, "按Tab键可以切换菜单");
    REPLACE_STRING(4468, "家族没有加入任何联盟");
    REPLACE_STRING(4509, "已获得");
    REPLACE_STRING(4510, "未获得");
    REPLACE_STRING(4512, "组队任务");
    REPLACE_STRING(4517, "展开背包");
    REPLACE_STRING(4518, "收缩背包");
    REPLACE_STRING(4520, "你可以在商城扩展背包格子");
    REPLACE_STRING(4581, "%d 天");
    REPLACE_STRING(4602, "请输入你想邀请的同学。\r\n你们必须处于相同频道相同地图。");
    REPLACE_STRING(4603, "请输入你想移除的同学");
    REPLACE_STRING(4604, "加入学院");
    REPLACE_STRING(4605, "(学院没有成员)");
    REPLACE_STRING(4606, "(没有校长)");
    REPLACE_STRING(4607, "(没有老师)");
    REPLACE_STRING(4608, "(没有创建学院)");
    REPLACE_STRING(4609, "[请添加同学]");
    REPLACE_STRING(4610, "%s 学院");
    REPLACE_STRING(4611, "老师(%d 人)");
    REPLACE_STRING(4612, "同学(%d 人)");
    REPLACE_STRING(4613, "你输入的玩家不存在或者不在线");
    REPLACE_STRING(4614, "你不能添加这名玩家为同学");
    REPLACE_STRING(4615, "你们在同一个学院");
    REPLACE_STRING(4616, "你们不属于同一个学院");
    REPLACE_STRING(4617, "你邀请的玩家不存在");
    REPLACE_STRING(4618, "你们必须在同一个地图");
    REPLACE_STRING(4619, "玩家已经是别人的学生了");
    REPLACE_STRING(4620, "你邀请的玩家必须比你等级低");
    REPLACE_STRING(4621, "你和对方等级不能超过20级");
    REPLACE_STRING(4622, "对方必须超过10级");
    REPLACE_STRING(4680, "该道具已经上锁了");
    REPLACE_STRING(4681, "你使用了 %s, 该装备可以交易一次");
    REPLACE_STRING(4682, "#c使用 %s 可以允许装备交易一次.#");
    REPLACE_STRING(4781, "%d : %d");
    REPLACE_STRING(5007, "百宝箱 : %s 从 %s 的 %s 抽到了 [%s] 让我们祝贺 Ta！");
    REPLACE_STRING(5070, "该道具无法升级");
    REPLACE_STRING(5074, "金锤子强化次数 : %d");
    REPLACE_STRING(5075, "金锤子强化次数 : 2 (满)");
    REPLACE_STRING(5223, "仅允许账号内转移");
    REPLACE_STRING(5267, "你使用了 原地复活术 (剩余 %d 个)");
    REPLACE_STRING(5288, "未完成");
    REPLACE_STRING(5298, "道具将于 %04d/%d/%d %02d:%02d 解锁");
    REPLACE_STRING(5300, "唯一装备");
    REPLACE_STRING(5305, "你想丢弃多少金币？");
    REPLACE_STRING(5320, "已获得的勋章数：%d");
    REPLACE_STRING(5321, "可以挑战");
    REPLACE_STRING(5322, "挑战中");
    REPLACE_STRING(5333, "低于10级无法组队");
    REPLACE_STRING(5341, "你获得了勋章!");
    REPLACE_STRING(5438, "交易币不足，还缺 %s x%d");
    REPLACE_STRING(5442, "获取%s栏物品 (%s %d个)");
    REPLACE_STRING(5443, "获取%s栏物品 (%s)");
    REPLACE_STRING(5451, " %d 天");
    REPLACE_STRING(5457, "你确定要购买吗？\r\n背包剩余 %s x%d");
    REPLACE_STRING(5463, "快捷键区域也会同时被还原。");
    REPLACE_STRING(5464, "快捷键区域也会同时被还原。");
    REPLACE_STRING(5514, "邀请 %s 加入你的队伍。");
    REPLACE_STRING(5515, "你已经邀请过 %s 了");
    REPLACE_STRING(5516, "%s 已经有队伍了");
    REPLACE_STRING(5619, "你没有足够的金币");
    REPLACE_STRING(5820, "%d 件套效果 :");
    REPLACE_STRING(5897, "双刀职业可佩戴\r\n");
    REPLACE_STRING(5906, "刀");
    REPLACE_STRING(6168, " 充值: %d");
    REPLACE_STRING(6254, "将悄悄话对象设置为 %s");
    REPLACE_STRING(6257, "你要删除好友 %s 吗？");
    REPLACE_STRING(6260, "%s 已过期，系统从你的背包里移除了。");
    REPLACE_STRING(6261, "%s 已经被系统从你的背包里移除。");
    REPLACE_STRING(6262, "%s 不能被修改或删除");
    REPLACE_STRING(6264, "(相同频道)双击发送悄悄话");
    REPLACE_STRING(6273, "你的家族加入了 [%s] 联盟");
    REPLACE_STRING(6274, "家族 [%s] 加入联盟");
    REPLACE_STRING(6275, "[最高等级: %d]\r\n");
    REPLACE_STRING(6276, "双击编辑分组");
    REPLACE_STRING(6277, "双击发送悄悄话");
    REPLACE_STRING(6278, "双击发送留言");
    REPLACE_STRING(6281, "不要再显示这个信息");
    REPLACE_STRING(6282, "当前地图无法使用该技能");
    REPLACE_STRING(6294, "对联盟");
    REPLACE_STRING(6300, "对远征队");
    REPLACE_STRING(6302, "默认分组");
    REPLACE_STRING(6312, "注册");
    REPLACE_STRING(6322, "举报");
    REPLACE_STRING(6323, "你无法提升技能");
    REPLACE_STRING(6324, "你不能对目标使用该技能");
    REPLACE_STRING(6325, "没有装备武器，无法使用该技能。");
    REPLACE_STRING(6341, "更换频道");
    REPLACE_STRING(6344, "键盘设置");
    REPLACE_STRING(6345, "将好友移入该分组");
    REPLACE_STRING(6346, "玩家信息");
    REPLACE_STRING(6347, "玩家信息 (%s)");
    REPLACE_STRING(6380, "任务指引目前没有任务");
    REPLACE_STRING(6381, "任务 (%s)");
    REPLACE_STRING(6595, "#fUI/UIWindow2.img/QuestIcon/7/0# %d 金币\\r\n");
    REPLACE_STRING(6596, "#fUI/UIWindow2.img/QuestIcon/8/0# %d 经验值\r\n");
    REPLACE_STRING(6641, "低等级任务");
    REPLACE_STRING(6643, "隐藏可接任务");
    REPLACE_STRING(6644, "显示可接任务");
    REPLACE_STRING(6650, "可接任务: %d");
    REPLACE_STRING(6654, "你确定要使用这个道具吗？");
    REPLACE_STRING(6664, "你没有[任务信使爱丽丝]\r\n你要去商城购买吗？");
    REPLACE_STRING(6671, " 点券");
    REPLACE_STRING(6672, " 金币");
    REPLACE_STRING(6679, "%d 天");
    REPLACE_STRING(6698, "分类 : ");
    REPLACE_STRING(6704, "完成");
    REPLACE_STRING(6705, "敏捷 :");
    REPLACE_STRING(6722, "智力 :");
    REPLACE_STRING(6728, "物品");
    REPLACE_STRING(6730, "运气 :");
    REPLACE_STRING(6731, "等级要求 : %d");
    REPLACE_STRING(6734, "魔法师");
    REPLACE_STRING(6740, "(空)");
    REPLACE_STRING(6742, "在线成员数 / 总成员数");
    REPLACE_STRING(6752, "任务");
    REPLACE_STRING(6753, "力量 :");
    REPLACE_STRING(6763, "该道具丢弃后就会消失，\n你确定要丢弃吗？");
    REPLACE_STRING(6792, "悄悄话");
    REPLACE_STRING(6795, "你没有足够的金币。");
    REPLACE_STRING(6796, "被家族开除了");
    REPLACE_STRING(6798, "补充成功");
    REPLACE_STRING(6799, "背包满了");
    REPLACE_STRING(6849, "金币");


}